builders:
  nuvigator:
    import: "package:nuvigator/builder.dart"
    builder_factories: ["nuvigationBuilder"]
    build_extensions: {".dart": [".nuvigation.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
