name: nuvigator
description: Routing and Navigation package.
version: 0.1.0
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_to_regexp: ^0.2.1
  
dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
