name: routing
description: Routing package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nuds:
    path: ../nuds
  provider: ^3.0.0+1
  path_to_regexp: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
