name: nuvigator
description: Flutter Routing and Navigation package.
version: 0.1.0
authors:
  - Nubank <tech@nubank.com.br>
  - Leonardo Iacovini <leonardo.iacovini@nubank.com.br>
  - Lucas Britto <lucas.britto@nubank.com.br>

homepage: https://github.com/nubank/nuvigator

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  build_config: ^0.4.0
  build: ^1.1.4
  code_builder: ^3.2.0
  source_gen: ^0.9.4+2
  analyzer: ^0.38.5
  dart_style: ^1.3.3
  flutter:
    sdk: flutter
  path_to_regexp: ^0.2.1

dev_dependencies:
  mockito: ^4.1.0
  build_runner: ^1.6.5
  flutter_test:
    sdk: flutter
